# Generated by Django 6.0.7 on 2026-09-01 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_owner_project_assignee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='assignee',
            new_name='owner',
        ),
    ]
